name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: olavodd42
          outputs: dist/snake-dark.svg
          # 🎨 Estilo hacker (verde neon em fundo preto)
          color_snake: "#00FF00"
          color_dots: "#00FF00,#39FF14,#7CFC00"
          background: "#000000"
          svg-embed-style: |
            .background { fill: #000000 }
            .snake { stroke: #00FF00 }
            .food { fill: #39FF14 }

      - name: Push Snake to output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
